name: "CONFIG COLLECTOR"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python
        run: |
          cd xray_config_tester
          pip install requests
          pip install pysocks
          chmod 777 Link2Json.jar
          chmod 777 xray-linux-amd64-1.8.3
          cd ..

      - name: Execute PHP script
        run: |
          php collect.php
          git config --global user.email "hosein.laletaheri@gmail.com"
          git config --global user.name "taheri79"
          git config credential.helper store
          git config pull.rebase false
          git add -A
          git commit -m "🚀 Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git pull
          git push
