name: "Test Java"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: cd xray_config_tester && java -jar Link2Json.jar -o output.json "vless://3a189725-1700-40ca-8dfa-aa63983666dd@vpncustomize.cam:443?encryption=none&security=reality&sni=www.iranserver.com&fp=firefox&pbk=55xH-tqPd6c0VZpbwlxRxhmfvp9lVUtp45CDJLpcw2I&sid=6b0541cd&spx=%2F&type=grpc&serviceName=%40VPNCUSTOMIZE&mode=gun#REALITY%20%7C%20DE%F0%9F%87%A9%F0%9F%87%AA%20%7C%2095ms%20%7C%200%EF%B8%8F%E2%83%A32%EF%B8%8F%E2%83%A3"

      - name: Execute PHP script
        run: |
          git config --global user.email "hosein.laletaheri@gmail.com"
          git config --global user.name "taheri79"
          git config credential.helper store
          git config pull.rebase false
          git add -A
          git commit -m "test java - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git pull
          git push